version: '3.4'

services:
  dwbot:
    image: dkrishen/dw-bot:demo-1.7
    container_name: dw-bot
    environment:
      - BotConfiguration__BotToken=<token>
    restart: always
    volumes:
      - ./database/:/app/database/:rw
      - ./logs/:/app/logs/:rw