version: '3.4'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/
    restart: always
  dwbot:
    image: dkrishen/dw-bot:demo-1.1
    container_name: dw-bot
    depends_on:
      - sqlite3
    environment:
      - BotConfiguration__BotToken=$BOTTOKEN
    restart: always
      
